### ISSUE TITLE
Quick question 

### ISSUE THREAD

**Issue by TomerGamerTV** [leminlimez/Nugget#1]
When you said “Works on all versions iOS 16.0+”, are you telling me this will work on an iPhone 11 running iOS 17.1?

**Comment by TomerGamerTV** [comment]
Amm can confirm that it works but why nowhere is it written that it formats the iPhone? Also is it possible to revert it?

**Comment by nathblade16** [comment]
> Amm can confirm that it works but why nowhere is it written that it formats the iPhone? Also is it possible to revert it?

it doesn't

**Comment by nathblade16** [comment]
> Amm can confirm that it works but why nowhere is it written that it formats the iPhone? Also is it possible to revert it?

you need to click continue with partial setup
