### ISSUE TITLE
EUEnabler not working.

### ISSUE THREAD

**Issue by kaya123k** [leminlimez/Nugget#10]
EUEnabler not working i tried both methods. When ipad (9th gen ios 18.1 beta4) boots nothing changes and nugget says success.

**Comment by chuckfluid** [comment]
Does not work iOS 18.1 B4 16 PM. Tried multiple times method 1/2 updating the MobileGestalt each time. Still no success.

**Comment by mrafieefard** [comment]
Any update?

**Comment by loqimean** [comment]
I have tested on iphone 11 Pro (iOS 17.6) and 12 Pro (iOS 18 stable) - doesn't work EU Enabler :-(

**Comment by darkzone89** [comment]
iOS 18.0 - iPhone 15 Pro Max - Not working

**Comment by Foodie947** [comment]
iOS 17.6.1, nothing works, but it says my gestalt file is not valid

**Comment by Crxaw** [comment]
Doesn't work on any iOS after 17.6. **NO IOS 18** stop asking for it.
