### ISSUE TITLE
Error! Myexception: Myexception("got an error message: ('MessageType': Restlet', "Number: 183]")      /   Nugget

### ISSUE THREAD

**Issue by drassell** [leminlimez/Nugget#116]
After installing Apple Intelligence, I wanted to return Face ID, but I can't do it because this error appears... HELP ME FIX IT (iPhone 11 Pro)

![Screenshot_3](https://github.com/user-attachments/assets/d3ef04a3-492d-4921-89cd-9feb3aad4eaf)
![Screenshot_1](https://github.com/user-attachments/assets/cd9e3945-be32-4c71-826c-7b413faf841c)

**Comment by zp-86** [comment]
Dont know the error, but have you made sure your device is on and unlocked? Did you hit trust this computer?

**Comment by leminlimez** [comment]
you did not unlock and trust the computer on your mobile device

**Comment by drassell** [comment]
Yes, I confirmed the trust


Вт, 5 нояб. 2024 г. в 18:38, leminlimez ***@***.***>:
