### ISSUE TITLE
Can't join Apple Intelligence waitlist

### ISSUE THREAD

**Issue by i486nugget** [leminlimez/Nugget#122]
# Joining does nothing. I really want to join so I can later enable face ID again
(iPhone XR running iOS 18.2 Beta 2, spoofed to iPhone 15 Pro)

https://github.com/user-attachments/assets/6b96b0e8-92f1-4e1a-91ac-cefcae2e039b

**Comment by NuggyNet** [comment]
well I got it to work but Siri doesn't have the new UI
