### ISSUE TITLE
Linux issue

### ISSUE THREAD

**Issue by Waffler2175** [leminlimez/Nugget#13]
Every time I run it in Linux, no matter the version, I always get the same error![image](https://github.com/user-attachments/assets/40f7a9d6-4416-4f58-bc25-aed59850ed0f)

**Comment by leminlimez** [comment]
thats an issue with pymobiledevice3, will see if there is anything i can do to fix it

**Comment by leminlimez** [comment]
Linux needs libimobiledevice and usbmuxd downloaded for it to work. I added error handling for this in v4.0 so it should not outright crash anymore
