### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by cwl1002** [leminlimez/Nugget#146]
Apple intelligence download is stuck, and some of the downloaded uis are wrong. There is no ChatGPT option in the settings. What should I do to solve it?

**Comment by cwl1002** [comment]
> Apple intelligence download is stuck, and some of the downloaded uis are wrong. There is no ChatGPT option in the settings. What should I do to solve it?

**Comment by SerStars** [comment]
https://github.com/leminlimez/Nugget/issues/147
