### ISSUE TITLE
How to Use Nugget Mobile Version ？

### ISSUE THREAD

**Issue by 123userxiaoG** [leminlimez/Nugget#148]
Where are the matching files?Plist file cannot be selected and cannot be used on ipad.What to do?

**Comment by 123userxiaoG** [comment]
![image](https://github.com/user-attachments/assets/45fd298e-70c9-4623-af22-22280cbd425d)

**Comment by SerStars** [comment]
This isn't the right repo + the mobile version has been archived and you can find it here: https://github.com/leminlimez/Nugget-Mobile
