### ISSUE TITLE
Does it work on IOS 18.2 Public Beta?

### ISSUE THREAD

**Issue by Sondae1** [leminlimez/Nugget#151]
Hi there,

I tried to spoof my Iphone 16 Pro Max with Nugget for Windows. I did all the steps, it reboots and says "Succes" but no Apple Intellicence. I'm in Europe. Any help would be appreciated.

**Comment by LutzRFrank** [comment]
I assume you changed the languages ... and you see Intelligence not available in your region? If you are in the EU you will need to log into the Appstore with an US AppleAccount to make it work

**Comment by SerStars** [comment]
Apple Intelligence is not available in Europe whether you use Nugget or not.
You'll need to create an US Apple Account.
