### ISSUE TITLE
PHONE KEYPAD ISSUE

### ISSUE THREAD

**Issue by Gamerr01** [leminlimez/Nugget#153]
After using the "Modify resolution" for the Dynamic Island, my phone app keypad has shrinked, leaving a lot of space around the numbers. Please help. 

Find attached screenshot. 

![image](https://github.com/user-attachments/assets/21e87d53-bce1-476a-a55e-1f716c35f4b5)

**Comment by leminlimez** [comment]
that is how modifying the resolution works. only fix is to revert the option
