### ISSUE TITLE
Spoofing None....

### ISSUE THREAD

**Issue by nitol** [leminlimez/Nugget#154]
I have tried so many times to bring back my face id + AI by following everything correctly, every time i got back face id but AI stoops working. It stuck at downloading-99%. I tried spoofing after confirmed that AI fully downloaded but no result/luck. 
Device 12 pro max and ios 18.2b2.
Need help on this regards.
Thanks in advance.

**Comment by Agustine808** [comment]
me too facing the same problem,after completing all the step successfully when i spoofed to none to fix camera and display on my iphone 15 they fixed but apple inteligence keep showing its downloading which never stops,need help please.

**Comment by techtalkf11** [comment]
Same here on my iPad Pro 11 (2020). It works when the device is spoofed, but when reverting to "none" it's becomes stuck on downloading.

**Comment by loqimean** [comment]
the same thing

**Comment by leminlimez** [comment]
Current workaround:
1. Close Nugget and reopen it
2. Go to Eligibility and click "Enable Apple Intelligence". **Do not touch the spoof model dropdown menu.**
3. Apply.
If that does not work, click the "Reset Mobile Gestalt" button.

A fix will come next update.

**Comment by nitol** [comment]
> Current workaround:
> 
> 1. Close Nugget and reopen it
> 
> 2. Go to Eligibility and click "Enable Apple Intelligence". **Do not touch the spoof model dropdown menu.**
> 
> 3. Apply.
> 
> If that does not work, click the "Reset Mobile Gestalt" button.
> 
> 
> 
> A fix will come next update.

Thank you so much for your support. No luck here also. Tried all several times. Eagerly waiting for the solution. Thanks again.

**Comment by leminlimez** [comment]
the reset mobile gestalt button should work, samr with using your original mobilegestalt file

**Comment by DrJapan** [comment]
> Current workaround:
> 
> 1. Close Nugget and reopen it
> 2. Go to Eligibility and click "Enable Apple Intelligence". **Do not touch the spoof model dropdown menu.**
> 3. Apply.
>    If that does not work, click the "Reset Mobile Gestalt" button.
> 
> A fix will come next update.

When do we use these steps? Is this for the first time? We shouldn't have to spoof the device at all, or de we have to do it the first time, to get AI to download?

**Comment by nitol** [comment]
> the reset mobile gestalt button should work, samr with using your original mobilegestalt file

Yes original gestalt brings back face id but tweaks and AI become absent then. Thing is like- we cannot have face id and AI together.
I am still trying in different ways...

Best regards.

**Comment by DrJapan** [comment]
I wonder if there's an eligibility.plist, just like macOS? Once we switch back to our original devices, that plist blocks access.

**Comment by DrJapan** [comment]
So far, I did excatly what you wrote.

I reopened Nugget, and just checked the one box. I used my clean mobilegestalt and applied it. I haven't gone into the settings to check, but so far the UI has remained.

**Comment by nitol** [comment]
Okay Guys, finally succeeded. 😇
AI and Face id both working in my 12 pro max ( after minimum 200 times tries ☺️ ). Here what i did- you can try in your's
- i selected spoof model 16 pro max as mine one is pro max model. I didn't chose many tweaks, just 16 pro max dynamic display, always on and AI options.
- after confirming that AI is fully downloaded, remove/delete existing gestalt from Files(where you saved) and get a fresh one.
- delete the used gestalt file from your computer and put the fresh one.
- select same tweaks(i suggest you to chose minimum tweaks which actually you need and works in your device) and all AI options of course.
- DO NOT TOUCH THE SPOOF MENU
- select the fresh gestalt and apply.
---- BOOM!!
