### ISSUE TITLE
PasswordRequiredError Msg

### ISSUE THREAD

**Issue by Trapa-Eureka** [leminlimez/Nugget#155]
I downloaded the '[Nugget_macOS_arm.zip]' file, decompressed it, and ran the program, but I get the following error message. I wonder why.

Error msg : PasswordRequiredError: PasswordRequiredError('PasswordProtected', '00008130-0008590924298D3A')

> macbook m1pro 
> iphone 15 pro max

The two devices were connected by a USB-c type cable.

what should i do?

![Screenshot 2024-11-11 at 2 28 12 PM](https://github.com/user-attachments/assets/5a2b7b22-5006-4dd2-b3ed-1acdc9cce403)

**Comment by loqimean** [comment]
just unlock your device and tap `trust this device` :-)

**Comment by leminlimez** [comment]
will improve error messages next update

**Comment by SerStars** [comment]
This has been fixed in 4.1.
