### ISSUE TITLE
Apple intelligence breaks my se 2022

### ISSUE THREAD

**Issue by Erlingas123** [leminlimez/Nugget#157]
So i tried to get apple intelligence on my se 2022. it didnt work  and i got a message that my camera doesnt work and went to remove all tweaks and reset mobile gestalt but the message never went away. i also think that it broke my ios updates. On ios 18.2

**Comment by loqimean** [comment]
I guess that's because device wasn't changed back to SE when you tried to enable AI. So, set device to NONE at this tab and try again. Cause problems with devices appears after changing device name, like after changing my iphone 12 pro device name to 15 pro I have issue with Face ID

**Comment by leminlimez** [comment]
#154

**Comment by Erlingas123** [comment]
it sadly still didnt work. i tried to restore it while keeping data and it still pops up. the camera works fine. i even tried to go into the diagnostic tool that apple made with ios 18 but no luck

**Comment by xCassidi** [comment]
To restore everything broken. Just use the mobilegestalt you pulled initially and click apply without changing anything else.
Also u gota give it a few hours to download AppleIntelligence. Keep the screen ON and on the Apple Intelligence settings page for it to download faster. Tried on 12mini.

**Comment by Erlingas123** [comment]
> To restore everything broken. Just use the mobilegestalt you pulled initially and click apply without changing anything else. Also u gota give it a few hours to download AppleIntelligence. Keep the screen ON and on the Apple Intelligence settings page for it to download faster. Tried on 12mini.

I have also tried that too but it still didn’t work. I guess ill try it another time
