### ISSUE TITLE
Nugget 4.0.1 is not longer available when I update to IOS18.2 beta3

### ISSUE THREAD

**Issue by sigma-skibiditoilet** [leminlimez/Nugget#158]
![IMG_2021](https://github.com/user-attachments/assets/2ba6907e-4837-4e30-9caf-b0a8292f372c)
It shown: connectionterminatederror:%0AConnectionTerminatedError
And I can’t change anything with my Mac, I think apple was fix this bug, and I also can’t turn on Apple Intelligence in EU.

**Comment by leminlimez** [comment]
apple patched it, I won't be fixing it

**Comment by DrJapan** [comment]
Awwww.

**Comment by sigma-skibiditoilet** [comment]
**I will keep this issue for a week, if we don’t find any solution, I will close this issue as not planned.**

**Comment by sigma-skibiditoilet** [comment]
**I'm trying to persuade those who are still on iOS 18.2 beta 2 or below, because iOS 18.2 beta 3 doesn't have any new features (for now). And it blocks the vulnerability, so please don't update until the problem is resolved!! if you really want to update, Just pretend I didn't say anything.**

**Comment by DrJapan** [comment]
I figured it might fix the image playground issue.

**Comment by reedary** [comment]
What about iPad ?  (那iPad呢，支持到哪个版本？）

**Comment by dragonbg** [comment]
bruh i literally just saw a random reddit thread about this and i was still on 18.0 so i just upgraded to 18,3 cuz i figured itd had to be the newest , i get on nugget I try apply and I get this same error and just now finding out, please update it!

**Comment by DrJapan** [comment]
> bruh i literally just saw a random reddit thread about this and i was still on 18.0 so i just upgraded to 18,3 cuz i figured itd had to be the newest , i get on nugget I try apply and I get this same error and just now finding out, please update it!

Beta 2 is still signed, so you can restore to that.

**Comment by dragonbg** [comment]
> > bruh i literally just saw a random reddit thread about this and i was still on 18.0 so i just upgraded to 18,3 cuz i figured itd had to be the newest , i get on nugget I try apply and I get this same error and just now finding out, please update it!
> 
> Beta 2 is still signed, so you can restore to that.

how

**Comment by DrJapan** [comment]
> > > bruh i literally just saw a random reddit thread about this and i was still on 18.0 so i just upgraded to 18,3 cuz i figured itd had to be the newest , i get on nugget I try apply and I get this same error and just now finding out, please update it!
> > 
> > 
> > Beta 2 is still signed, so you can restore to that.
> 
> how

Download your ipsw, from here:
https://ipsw.dev/product/iPhone

Then try updating back to beta 2, but I suspect you'll have to completely restore, so be prepared to loose files.

**Comment by JonathanGurkan** [comment]
What are the plans for nugget?

**Comment by SanketRohilla** [comment]
> > > > bruh i literally just saw a random reddit thread about this and i was still on 18.0 so i just upgraded to 18,3 cuz i figured itd had to be the newest , i get on nugget I try apply and I get this same error and just now finding out, please update it!
> > > 
> > > 
> > > Beta 2 is still signed, so you can restore to that.
> > 
> > 
> > how
> 
> Download your ipsw, from here: https://ipsw.dev/product/iPhone
> 
> Then try updating back to beta 2, but I suspect you'll have to completely restore, so be prepared to loose files.
> 
> UPDATE: I was able to just update back to beta 2.

did you loose files?

**Comment by sigma-skibiditoilet** [comment]
> > > > > bruh i literally just saw a random reddit thread about this and i was still on 18.0 so i just upgraded to 18,3 cuz i figured itd had to be the newest , i get on nugget I try apply and I get this same error and just now finding out, please update it!
> > > > 
> > > > 
> > > > Beta 2 is still signed, so you can restore to that.
> > > 
> > > 
> > > how
> > 
> > 
> > Download your ipsw, from here: https://ipsw.dev/product/iPhone
> > Then try updating back to beta 2, but I suspect you'll have to completely restore, so be prepared to loose files.
> > UPDATE: I was able to just update back to beta 2.
> 
> did you loose files?

You can’t transfer your backup from your high vision to low vision

**Comment by SanketRohilla** [comment]
> > > > > > bruh i literally just saw a random reddit thread about this and i was still on 18.0 so i just upgraded to 18,3 cuz i figured itd had to be the newest , i get on nugget I try apply and I get this same error and just now finding out, please update it!
> > > > > 
> > > > > 
> > > > > Beta 2 is still signed, so you can restore to that.
> > > > 
> > > > 
> > > > how
> > > 
> > > 
> > > Download your ipsw, from here: https://ipsw.dev/product/iPhone
> > > Then try updating back to beta 2, but I suspect you'll have to completely restore, so be prepared to loose files.
> > > UPDATE: I was able to just update back to beta 2.
> > 
> > 
> > did you loose files?
> 
> You can’t transfer your backup from your high vision to low vision

but he said he just able to update it not restore

**Comment by SanketRohilla** [comment]
> > > > > > bruh i literally just saw a random reddit thread about this and i was still on 18.0 so i just upgraded to 18,3 cuz i figured itd had to be the newest , i get on nugget I try apply and I get this same error and just now finding out, please update it!
> > > > > 
> > > > > 
> > > > > Beta 2 is still signed, so you can restore to that.
> > > > 
> > > > 
> > > > how
> > > 
> > > 
> > > Download your ipsw, from here: https://ipsw.dev/product/iPhone
> > > Then try updating back to beta 2, but I suspect you'll have to completely restore, so be prepared to loose files.
> > > UPDATE: I was able to just update back to beta 2.
> > 
> > 
> > did you loose files?
> 
> You can’t transfer your backup from your high vision to low vision

also can you help me itunes not detecting my iphone

**Comment by SanketRohilla** [comment]
UPDATE : Use 3u tools to go back to beta 2 without lossing any files

**Comment by leminlimez** [comment]
> > apple patched it, I won't be fixing it
> 
> I saw somewhere it might be due to the file size of Apple Intelligence, is there a way you can split it into chunks or switch over to libimobiledevice or maybe change the SSL ish

that is completely wrong

**Comment by sgardeleee** [comment]
hello what is goin to hapen can we fix this problem? or nugget is dead for new versions
i wish it will fix. its very nice tool

**Comment by DrJapan** [comment]
> > > > > > > bruh i literally just saw a random reddit thread about this and i was still on 18.0 so i just upgraded to 18,3 cuz i figured itd had to be the newest , i get on nugget I try apply and I get this same error and just now finding out, please update it!
> > > > > > 
> > > > > > 
> > > > > > Beta 2 is still signed, so you can restore to that.
> > > > > 
> > > > > 
> > > > > how
> > > > 
> > > > 
> > > > Download your ipsw, from here: https://ipsw.dev/product/iPhone
> > > > Then try updating back to beta 2, but I suspect you'll have to completely restore, so be prepared to loose files.
> > > > UPDATE: I was able to just update back to beta 2.
> > > 
> > > 
> > > did you loose files?
> > 
> > 
> > You can’t transfer your backup from your high vision to low vision
> 
> but he said he just able to update it not restore

If on Mac, hold down the option key, then press update in Finder. If on a PC, then hold down shift, and then click update. After either action, a window will popup, and you can choose the ipsw, you would like to restore to.

**Comment by DrJapan** [comment]
> > > > > bruh i literally just saw a random reddit thread about this and i was still on 18.0 so i just upgraded to 18,3 cuz i figured itd had to be the newest , i get on nugget I try apply and I get this same error and just now finding out, please update it!
> > > > 
> > > > 
> > > > Beta 2 is still signed, so you can restore to that.
> > > 
> > > 
> > > how
> > 
> > 
> > Download your ipsw, from here: https://ipsw.dev/product/iPhone
> > Then try updating back to beta 2, but I suspect you'll have to completely restore, so be prepared to loose files.
> > UPDATE: I was able to just update back to beta 2.
> 
> did you loose files?

Nope! Whew.

**Comment by adeshpande03** [comment]
> > > > > > bruh i literally just saw a random reddit thread about this and i was still on 18.0 so i just upgraded to 18,3 cuz i figured itd had to be the newest , i get on nugget I try apply and I get this same error and just now finding out, please update it!
> > > > > 
> > > > > 
> > > > > Beta 2 is still signed, so you can restore to that.
> > > > 
> > > > 
> > > > how
> > > 
> > > 
> > > Download your ipsw, from here: https://ipsw.dev/product/iPhone
> > > Then try updating back to beta 2, but I suspect you'll have to completely restore, so be prepared to loose files.
> > > UPDATE: I was able to just update back to beta 2.
> > 
> > 
> > did you loose files?
> 
> Nope! Whew.

I tried this and nearly bricked my phone. What were the exact steps you took?
