### ISSUE TITLE
Exception Occurs after trying to apply changes to iPhone SE iOS 18.2 Beta 3

### ISSUE THREAD

**Issue by ThunderboltCommunicationsCorp** [leminlimez/Nugget#164]
I'm getting the following error while trying to apply changes on my iPhone SE using nugget 4.0.1 and I don't know what to do to fix this please help.
![Annotation 2024-11-12 144338](https://github.com/user-attachments/assets/f549d8f3-67c9-4490-97b1-6778ab5d35c4)

**Comment by sigma-skibiditoilet** [comment]
You can try to downgrade your phone to iOS 18.2 beta 2 or under
That could be helpful

**Comment by leminlimez** [comment]
#158
