### ISSUE TITLE
image playground not working properly

### ISSUE THREAD

**Issue by neyarski** [leminlimez/Nugget#170]
after waiting for 2 weeks i finally got the access to image playground but after using it i can't do anything not even generating the emoji's and even the images any solution?

**Comment by DrJapan** [comment]
If you don't have a device with neural engine, your device won't be able to handle the requests.

iPhone 15 Pro, 15 Pro MAX and all iPhone 16 phones have a neural engine.

**Comment by neyarski** [comment]
> If you don't have a device with neural engine, your device won't be able to handle the requests.
> 
> 
> 
> iPhone 15 Pro, 15 Pro MAX and all iPhone 16 phones have a neural engine. 

so whats the point of the tool here cuz iphone 15pro -pro max can already have it without the tool
