### ISSUE TITLE
Dynamic Island 

### ISSUE THREAD

**Issue by Brodontmiss1019** [leminlimez/Nugget#172]
I have an Iphone Xr and I tried enabling dynamic island and I used the RDAR fix already mind you, (Great feature btw) But like half the island is underneath the Xr notch, and it would be like that for lots of the Iphones you see nowadays. It is kind of annoying, and I was wondering if there is something like a displacement option coming soon to play around with until you find whats best fits with the notch on each phone.
![{046572D2-0891-4E6F-AB07-0E9717D3E229}](https://github.com/user-attachments/assets/1f77566e-eb76-4354-a3c2-c99dceb8d6f7)

**Comment by Crxaw** [comment]
@Brodontmiss1019 This is the same for **EVERY** phone that doesn't support one.
