### ISSUE TITLE
iPhone 14 Pro iOS 18.2 beta 2 not completing download

### ISSUE THREAD

**Issue by goodzeeak** [leminlimez/Nugget#173]
I got it to work without having Face ID, once I've re-enabled Face ID it has gone to downloading and is stuck at 99%

Is there currently a fix for this?

Oh and by the way a big thanks to the devs for making this possible when Apple just love to gate everything behind a paywall 😂👌

**Comment by smailpouri** [comment]
I'm on iPhone 14 Pro too. 
I don't if something has change but it does not really works for me. 

My experience:

- iOS 18.1
>Apple Intelligence will work but no **writing tool, or anything else.** 
> Face ID fix works the first time, Apple Intelligence animation is gone. 
> after repeating steps, Face ID fix won't work, even starting from scratch. 
Maybe I'm missing something. 

- iOS 18.2 beta 2
> same issues and same benefits
> ChatGPT integration will work. 

- Each time a tweak is applied: 
> General > Privacy&Security > Tracking > **Allow Apps To Request to Track = ON** 
> Developer App Certificate need to be "**Trusted**" again

Not having Face ID makes this a bit cumbersome, ended up deactivating the all thing.

**Comment by smailpouri** [comment]
> I got it to work without having Face ID, once I've re-enabled Face ID it has gone to downloading and is stuck at 99%
> 
> Is there currently a fix for this?
> 
> Oh and by the way a big thanks to the devs for making this possible when Apple just love to gate everything behind a paywall 😂👌



Make sure to turn Apple Intelligence OFF before applying the Face ID fix.

**Comment by SerStars** [comment]
#185
