### ISSUE TITLE
Download grading to IOS 18.2 beta 2 

### ISSUE THREAD

**Issue by Raymantra1st** [leminlimez/Nugget#175]
I want to downgrade to iOS 18.2 with 3utools and I saw an option (to retain data) will I loose files or apps if I use that prompt???

**Comment by nitol** [comment]
No, retain data means it will keep all your data with new ios flash.

**Comment by Raymantra1st** [comment]
So I can proceed ??

**Comment by nitol** [comment]
Yes

**Comment by Raymantra1st** [comment]
Thank you I was able to downgrade 18.2 beta 2 and it was a success no loss of data or apps

**Comment by AngelP216** [comment]
did the 3utools cost and is it possible to do the same thing with itunes or will i lose data

**Comment by SerStars** [comment]
> is it possible to do the same thing with itunes or will i lose data
 You will lose your data.

**Comment by Raymantra1st** [comment]
I didn’t loose any data it worked

**Comment by AngelP216** [comment]
> I didn’t loose any data it worked

What did you use I tunes? Or 3utools
