### ISSUE TITLE
AOD not turning off when face-down or in-pocket

### ISSUE THREAD

**Issue by xCassidi** [leminlimez/Nugget#182]
Always On Display AOD should turn off when sensor is covered to prevent screen burn in. That is not working, tested on 12mini 18.2pb1. Thankyou.

**Comment by SerStars** [comment]
AOD is not meant for the phone you're using, so the sensors won't work for that.
(correct me if I'm wrong)

**Comment by xCassidi** [comment]
> AOD is not meant for the phone you're using, so the sensors won't work for that.
> 
> (correct me if I'm wrong)

Sir is there no way to make proximity sensor work with AOD tweak? If not, you may close this issue. Thankyou.

**Comment by SerStars** [comment]
> > AOD is not meant for the phone you're using, so the sensors won't work for that.
> > (correct me if I'm wrong)
> 
> Sir is there no way to make proximity sensor work with AOD tweak? If not, you may close this issue. Thankyou.

I'm not sure but I'll be closing this issue since no one else is commenting.
