### ISSUE TITLE
Fix Face ID = Turned Off The Siri 2.0

### ISSUE THREAD

**Issue by flann10** [leminlimez/Nugget#187]
hey i want ask something, i spoofed my iphone 11 with iphone 16 (iphone 17.3), and the apple intelligence/siri 2.0 worked perfectly after the device restarted and i waited few minutes till the download is done, but when i tried to fix the face id, after i spoofed device to none on nugget, after the restart for the first few sec (more likely the first minute after the phone turned back on), the apple intelligence/siri 2.0 is still available, but with short animation as usual (if im not wrong we needed to wait 1-5 minutes till the apple intelligence/siri 2.0 work perfectly), but after i waited for 5 minutes, all of the sudden the apple intelligence/siri 2.0 is gone and i got the old siri one, but the apple intelligence menu on settings is still available (i never clicked on the apple intelligence menu on settings after i spoofed the device to none) and the writing tools (compose with chat gpt) is still worked, then i tried to restart my device but after that the apple intelligence/siri 2.0 still not working, even the writing tools stopped working too

do you guys have any idea??, tysm

**EDIT : I've finally find the solution, i just need to use the iphone 16 pro max spoofed model and the newest [Nugget 4.1](https://github.com/leminlimez/Nugget/releases/tag/v4.1), and im using #185 method, and for the optional step for me is after i turned on the airplane mode, i waited till the apple intelligence works normally and after the apple intelligence work normally, i kept the airplane mode turned on for 5 more minutes, then after that i turned off the airplane mode and it worked.**

**Comment by xCassidi** [comment]
Try the solution proposed in issue#185. Im about to try it as well.
