### ISSUE TITLE
Apple Intelligence Glow cut from right and bottom

### ISSUE THREAD

**Issue by xCassidi** [leminlimez/Nugget#188]
Spoofed to 16promax on 12mini and the new AI glow is cut from right and bottom sides, screenshots attached. Spoofed to 16 too after it but no effect. Thankyou.
![image](https://github.com/user-attachments/assets/9f78eaf3-0a93-466d-a38e-ca389210a563)
![image](https://github.com/user-attachments/assets/ea3efd52-2d1f-436b-8c22-2f582f9ff051)

**Comment by leminlimez** [comment]
issue with the mini iphones, not fixable
