### ISSUE TITLE
ios 18.2 beta 3 is unsupported?

### ISSUE THREAD

**Issue by Agustine808** [leminlimez/Nugget#196]
new nugget version is unsupported for 18.2 beta 3 officially?

**Comment by SerStars** [comment]
Nugget 4.1 shows that 18.2 beta 3 is unsupported and the older versions don’t support 18.2 beta 3 too but they simply don’t show the message “Unsupported”

**Comment by Agustine808** [comment]
thanks for your response

**Comment by SerStars** [comment]
You're welcome
