### ISSUE TITLE
DO NOT USE VERSION 4.1 IT HAS A VIRUS USE 4.0.1

### ISSUE THREAD

**Issue by connorrosco** [leminlimez/Nugget#197]

**Comment by SerStars** [comment]
Let me guess, you got a alert that Nugget has malware/not trusted
That’s normal it doesn’t have malware or any kind of that

**Comment by leminlimez** [comment]
it does not have a virus, that is a false positive

**Comment by connorrosco** [comment]
Ok thank you very much and good job to nugget it's pretty good!

**Comment by connorrosco** [comment]
> Let me guess, you got a alert that Nugget has malware/not trusted
> 
> That’s normal it doesn’t have malware or any kind of that

Oh ok I use norton360 it said it found a file that was a virus thanks anyways!

**Comment by leminlimez** [comment]
norton is the real virus

**Comment by connorrosco** [comment]
> norton is the real virus

lol
