### ISSUE TITLE
unable to download version 4.1

### ISSUE THREAD

**Issue by pinkjimrussiagirl** [leminlimez/Nugget#203]
i am unable to download version 4.1 of nugget because my computer is detecting a virus in it and i cannot bypass it through any settings

**Comment by leminlimez** [comment]
windows?

starting to think github actions caused this, may have to reupload it

**Comment by connorrosco** [comment]
> i am unable to download version 4.1 of nugget because my computer is detecting a virus in it and i cannot bypass it through any settings

You could try and disable your antivirus while using it and re-enable after finished using it!

**Comment by pinkjimrussiagirl** [comment]
it's still doing it
![image](https://github.com/user-attachments/assets/b232069e-198d-4a39-9613-3fb9d6c97a7c)

**Comment by SerStars** [comment]
Try [this](https://github.com/leminlimez/Nugget/actions/runs/11873961780/artifacts/2197255246) since it works for me
