### ISSUE TITLE
[solved] FaceID is Now Complete - still not working after AppleIntelligence spoof to none

### ISSUE THREAD

**Issue by xCassidi** [leminlimez/Nugget#207]
![image](https://github.com/user-attachments/assets/8fdea639-0576-4328-a30c-207ffa9a82e5)
It gets to here and then stuck. Waited 5mins. FaceID not set up. Only using Apple Intelligence tweak and later switched spoof to none. Tested on 12mini. Thankyou.

**Comment by xCassidi** [comment]
Fix: set up passcode first. Then set up Face ID.

**Comment by Agustine808** [comment]
on iphone 15 after spoofing to none apple intelligence still not working!

**Comment by xCassidi** [comment]
> on iphone 15 after spoofing to none apple intelligence still not working!

If Face ID is broken refer to #185. If Face ID is working but not proceeding then let me know.

If you need help with #185. Also let me know i will guide you

**Comment by SerStars** [comment]
Since the issue has been solved in this issue, ill be closing it.
