### ISSUE TITLE
Reply to 4.1 threat

### ISSUE THREAD

**Issue by connorrosco** [leminlimez/Nugget#208]
![image](https://github.com/user-attachments/assets/3ef3b7af-e0e7-41f5-b170-bade73ea7a5b)

**Comment by leminlimez** [comment]
recompiled it, redownload from [releases](https://github.com/leminlimez/Nugget/releases/v4.1) and see if it still happens

**Comment by connorrosco** [comment]
> recompiled it, redownload from [releases](https://github.com/leminlimez/Nugget/releases/v4.1) and see if it still happens

ALR I'll try again

**Comment by SerStars** [comment]
closing this issue since its inactive any it pretty much works
