### ISSUE TITLE
Writing tools 

### ISSUE THREAD

**Issue by Ak-2077** [leminlimez/Nugget#212]

**Comment by Ak-2077** [comment]
I used method #185 and its really work but how to use writing tools is there any method to use it ????

**Comment by xCassidi** [comment]
> I used method #185 and its really work but how to use writing tools is there any method to use it ????
> 
> 

Only Compose with ChatGPT works in Writing Tools. Everything else requires Neural Engine which is not in unsupported iPhones so everything else is basically only showoff.

**Comment by Azemblage** [comment]
So writing tools don't work at all ?

tried on the iPhone xr and is the only thing not working - is there any work around to use it ?

**Comment by Ak-2077** [comment]
After five minutes, I’m not able to use Apple, intelligent and I use method #185 AndStuckInDownloading

**Comment by xCassidi** [comment]
> So writing tools don't work at all ?
> 
> tried on the iPhone xr and is the only thing not working - is there any work around to use it ?

Nothing actually works my guy. Apple Intelligence requires Neural Engine. What we get is just an imitation of the real thing its basically only cosmetics.

**Comment by xCassidi** [comment]
> After five minutes, I’m not able to use Apple, intelligent and I use method #185 AndStuckInDownloading

1. Spoof to 16promax.
2. Wait for it to download AI model (open Apple Intelligence settings screen for it to download faster)
3. Test and confirm AI is running.
4. Ready everything you have to do next> (turn AI off >spoof to none >airplane mode after restart)
4.1. Plug iPhone to PC. Set eligibility tweak to ON and spoof to NONE, select mobilegestalt.plist and goto APPLY screen (DO NOT APPLY TWEAKS YET, JUST READY)
4.2. Goto Apple Intelligence settings and test new Siri once again to confirm working, then turn AI OFF and quickly APPLY TWEAKS from PC to reboot iPhone.
5. As soon as iPhone reboots, switch on Airplane mode. Stay in airplane mode and test Siri after 1-2 minutes.
6. Once new Siri confirmed working a few times, stay on Airplane mode for 3-5 more minutes (and test new Siri periodically)
7. Turn off Airplane mode, remove Apple Intelligence Settings from Recent Apps and NEVER TOUCH Apple Intelligence Settings ever again.
8. ???
9. Enjoy

**Comment by SerStars** [comment]
closing this issue as its been answered
