### ISSUE TITLE
No Device detected

### ISSUE THREAD

**Issue by JevLOMCN** [leminlimez/Nugget#215]
Once I succecfully spoofed my IPhone 14 Pro Max (18.2) to 16 Pro Max, set up all the apple ai stuff and restrated to then unspoof to allow me to fix Face ID. Nugget,Itunes,Sideloady,3uTools wont detect my Iphone. 

I've tried using the [v4.1](https://github.com/leminlimez/Nugget/releases/tag/v4.1)

![image](https://github.com/user-attachments/assets/fc6a84a0-7a23-4f4e-8e7b-8193a3dc4104)

**Comment by hudthaman** [comment]
probably your cable tbh

**Comment by MasterMind-del** [comment]
> Once I succecfully spoofed my IPhone 14 Pro Max (18.2) to 16 Pro Max, set up all the apple ai stuff and restrated to then unspoof to allow me to fix Face ID. Nugget,Itunes,Sideloady,3uTools wont detect my Iphone.
> 
> I've tried using the [v4.1](https://github.com/leminlimez/Nugget/releases/tag/v4.1)
> 
> ![image](https://private-user-images.githubusercontent.com/68875342/387408155-fc6a84a0-7a23-4f4e-8e7b-8193a3dc4104.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NzE5MDMsIm5iZiI6MTczMTk3MTYwMywicGF0aCI6Ii82ODg3NTM0Mi8zODc0MDgxNTUtZmM2YTg0YTAtN2EyMy00ZjRlLThlN2ItODE5M2EzZGM0MTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDIzMTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMTkwM2RlZmVhNTdjY2FkNDA4YWVhZmE3NTkxMDljNTIzNDc0ZDg3NWVhMDdiYjdjYTNjZTQ3ZmZkOTFkNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.48QXzELH5MoamWCp6usXxyWsVrTIpRQ68cgChIeFZZM)

Have you applied python step before opening nuggets software?

**Comment by SerStars** [comment]
Click on the refresh button in Nugget and try again (if you haven't already)

**Comment by JevLOMCN** [comment]
Refreshing it didn't fix it but restarting my phone a few times did. Thank you all. I do however think this does need looking into by the devs, I'll close the issue.
