### ISSUE TITLE
18.1

### ISSUE THREAD

**Issue by voyyagge** [leminlimez/Nugget#219]
Does nugget 18.1 support and do I need to install python?( Windows)

**Comment by SerStars** [comment]
It would be great if you read the READNE.md file

> Sparserestore works on all versions iOS 17.0-17.7 and iOS 18.0-18.1 beta 4. There is partial support for iOS 17.7.1 and iOS 18.1b5-18.2 beta 2.

> **iOS 18.2 developer beta 3 (public beta 2) and newer is not supported.**

**Comment by SaladinoGW** [comment]
It dont mention 18.1 stable, 18.2 dev beta 3 is old than 18.1 stable? Idk…

**Comment by SerStars** [comment]
> It dont mention 18.1 stable, 18.2 dev beta 3 is old than 18.1 stable? Idk…

If it doesn't mention it.. it doesn't work????
