### ISSUE TITLE
[Pymobiledevice3Exception]-Domain name cannot contain a slash

### ISSUE THREAD

**Issue by biggunray** [leminlimez/Nugget#22]
I have a iPhone 13 currently running on iOS18.1 beta4. I am having trouble applying the modified gestalt file on my cellphone with Nugget 2.2. I have a windows 10 laptop and I have tried Nugget_windows and Nugget_python, but the error pops up with both methods. I have python 3.10 installed and I also upgraded pymobiledevice3, but that did not help. Did anyone face the same issue or have any clue what went wrong? 
![pyerror](https://github.com/user-attachments/assets/c2726645-7f91-4be8-85e1-19634c7478cf)

**Comment by leminlimez** [comment]
you are on iOS 18.1 beta 5

#21
