### ISSUE TITLE
That would be fine to support iOS 18 beta 5

### ISSUE THREAD

**Issue by loqimean** [leminlimez/Nugget#23]
I have an error "domain name cannot contain a slash". like this error log from another app:
![Image 25 09 2024 at 11 36 AM](https://github.com/user-attachments/assets/80334a80-5bbd-4b3f-a304-8a1aabb69ef9)

**Comment by i0Ek3** [comment]
Acturally no, because "Sparserestore was patched in iOS 18.1 beta 5. It will not be supported, please stop asking.".
