### ISSUE TITLE
Error setting WillEncrypt value in lockdown

### ISSUE THREAD

**Issue by AaoIi** [leminlimez/Nugget#230]
i am getting the below error when trying to enable apple intelligence on iOS 18.1, when following up all the instructions.

PyMobileDevice3Exception: PyMobileDevice3Exception("Device link error: {'ErrorCode': 1, 'ErrorDescription': 'Error setting WillEncrypt value in lockdown (MBErrorDomain/1). Underlying error: Cannot remove iTunes Backup Encryption - Encrypted Backup MDM setting present on device (MBErrorDomain/22).', 'MessageName': 'Response'}")

**Comment by MasterMind-del** [comment]
> i am getting the below error when trying to enable apple intelligence on iOS 18.1, when following up all the instructions.
> 
> PyMobileDevice3Exception: PyMobileDevice3Exception("Device link error: {'ErrorCode': 1, 'ErrorDescription': 'Error setting WillEncrypt value in lockdown (MBErrorDomain/1). Underlying error: Cannot remove iTunes Backup Encryption - Encrypted Backup MDM setting present on device (MBErrorDomain/22).', 'MessageName': 'Response'}")

I think attaching picture I’ll help us to know ur error

**Comment by leminlimez** [comment]
your mdm is requiring backup encryption be on, please do not use nugget on school/work devices

**Comment by AaoIi** [comment]
Note that i am not using it on work or school computer, i think the issue is that i used my computer to backup my iPhone, with encryption password on finder ( previously iTunes).
![Screenshot 2024-11-23 at 2 38 32 PM](https://github.com/user-attachments/assets/f3d0a786-6402-4a74-a64e-bf4352215c0b)

i own my laptop and i own my iPhone.

Do you have any insights of what is wrong?

**Comment by MasterMind-del** [comment]
> Note that i am not using it on work or school computer, i think the issue is that i used my computer to backup my iPhone, with encryption password on finder ( previously iTunes). ![Screenshot 2024-11-23 at 2 38 32 PM](https://private-user-images.githubusercontent.com/9898307/389194261-f3d0a786-6402-4a74-a64e-bf4352215c0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNjU1NjEsIm5iZiI6MTczMjM2NTI2MSwicGF0aCI6Ii85ODk4MzA3LzM4OTE5NDI2MS1mM2QwYTc4Ni02NDAyLTRhNzQtYTY0ZS1iZjQzNTIyMTVjMGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjNUMTIzNDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWFhMjE1OTU0MzlmNGMzNjhiNzBlZGQ0ZjFiNzYwZTE0NTY3NWMwNWMzYTJhYzBjOTNhZDFkYWYwY2NhNDU0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.5bCOF2U2DqEYExYKYq5BSZFO8k_yUFHSdG70S9gUu9A)
> 
> i own my laptop and i own my iPhone.
> 
> Do you have any insights of what is wrong?

The error message indicates that your MacBook has a managed configuration through MDM (Mobile Device Management), likely controlled by an organization, such as a school or workplace. To disable the MDM encryption or management, you would need administrative access, which depends on your situation:

Steps to Turn Off MDM Backup Encryption:

	1.	Check if You Have Admin Rights:
	•	Go to System Preferences > Users & Groups.
	•	Check if your account is labeled as an “Administrator.”
	2.	Remove MDM Profile (If You Have Admin Access):
	•	Open System Preferences > Profiles.
	•	Look for any profiles related to MDM and click Remove (-).
	3.	Erase and Reinstall macOS (If MDM Can’t Be Removed):
	•	If the MacBook is managed, the MDM profile might reappear after a reset unless unenrolled by the organization.
	•	Backup your data and perform a fresh macOS installation:
	•	Restart your Mac and hold Command (⌘) + R to enter Recovery Mode.
	•	Use Disk Utility to erase the disk, then reinstall macOS.
	4.	Contact the Organization:
	•	If the MacBook is from a school or workplace, you might need their permission or assistance to remove the MDM profile.
	5.	Use a Third-Party Tool (Optional):
	•	Tools like “iActivate” or “MDM Bypass” can remove MDM profiles, but this might violate policies or warranties.

If the MacBook isn’t managed by any organization, but this error persists, it’s possible the MDM profile was added previously. Let me know if you need detailed steps for any of these processes.

**Comment by AaoIi** [comment]
None of the above is the issue, the thing is that i backup my iPhone with encryption enabled, and that's why its not working, trying to remove or disable any backup is not even solving the issue
