### ISSUE TITLE
Broken minimuxer on ios 18.1 stable. iPhone 14 Pro Max

### ISSUE THREAD

**Issue by 7033bill** [leminlimez/Nugget#237]
I have iphone 14 pro max and it run ios 18.1 stable. I forgot to read the warning and now i broken minimuxer, i use nugget mobile to spoof device and enable apple intelligent and now my face id not working. How to revert device to default as before using nugget mobile without loss any data?

**Comment by MasterMind-del** [comment]
> I have iphone 14 pro max and it run ios 18.1 stable. I forgot to read the warning and now i broken minimuxer, i use nugget mobile to spoof device and enable apple intelligent and now my face id not working. How to revert device to default as before using nugget mobile without loss any data?

Follow the instructions on #185 to solve that issue quick

**Comment by 7033bill** [comment]
> > I have iphone 14 pro max and it run ios 18.1 stable. I forgot to read the warning and now i broken minimuxer, i use nugget mobile to spoof device and enable apple intelligent and now my face id not working. How to revert device to default as before using nugget mobile without loss any data?
> 
> Follow the instructions on #185 to solve that issue quick

Can i update to a newer version when available to revert device back to default and remove apple intelligent, and face id work again?

**Comment by MasterMind-del** [comment]
> > > I have iphone 14 pro max and it run ios 18.1 stable. I forgot to read the warning and now i broken minimuxer, i use nugget mobile to spoof device and enable apple intelligent and now my face id not working. How to revert device to default as before using nugget mobile without loss any data?
> > 
> > 
> > Follow the instructions on #185 to solve that issue quick
> 
> Can i update to a newer version when available to revert device back to default and remove apple intelligent, and face id work again?

If you don’t want to use any nuggets feature then just plug in your phone and head it to apply, select the file you created on the mobile device and hit apply. This will help you to restore the device to the default settings

**Comment by 7033bill** [comment]
> > > > I have iphone 14 pro max and it run ios 18.1 stable. I forgot to read the warning and now i broken minimuxer, i use nugget mobile to spoof device and enable apple intelligent and now my face id not working. How to revert device to default as before using nugget mobile without loss any data?
> > > 
> > > 
> > > Follow the instructions on #185 to solve that issue quick
> > 
> > 
> > Can i update to a newer version when available to revert device back to default and remove apple intelligent, and face id work again?
> 
> If you don’t want to use any nuggets feature then just plug in your phone and head it to apply, select the file you created on the mobile device and hit apply. This will help you to restore the device to the default settings

How to install nugget on mac os

**Comment by MasterMind-del** [comment]
> > > > > I have iphone 14 pro max and it run ios 18.1 stable. I forgot to read the warning and now i broken minimuxer, i use nugget mobile to spoof device and enable apple intelligent and now my face id not working. How to revert device to default as before using nugget mobile without loss any data?
> > > > 
> > > > 
> > > > Follow the instructions on #185 to solve that issue quick
> > > 
> > > 
> > > Can i update to a newer version when available to revert device back to default and remove apple intelligent, and face id work again?
> > 
> > 
> > If you don’t want to use any nuggets feature then just plug in your phone and head it to apply, select the file you created on the mobile device and hit apply. This will help you to restore the device to the default settings
> 
> And can i remove tweak using the mobile ges file, i don't have org mobile ges file. I ask first so if I don't have the original file I will do it your way, and if i have the file i will use the your above way tells me

To install nugget software on Mac, head over to code page and download the Mac software version check it well before proceeding the download. After that let me know

**Comment by 7033bill** [comment]
> > > > > > I have iphone 14 pro max and it run ios 18.1 stable. I forgot to read the warning and now i broken minimuxer, i use nugget mobile to spoof device and enable apple intelligent and now my face id not working. How to revert device to default as before using nugget mobile without loss any data?
> > > > > 
> > > > > 
> > > > > Follow the instructions on #185 to solve that issue quick
> > > > 
> > > > 
> > > > Can i update to a newer version when available to revert device back to default and remove apple intelligent, and face id work again?
> > > 
> > > 
> > > If you don’t want to use any nuggets feature then just plug in your phone and head it to apply, select the file you created on the mobile device and hit apply. This will help you to restore the device to the default settings
> > 
> > 
> > And can i remove tweak using the mobile ges file, i don't have org mobile ges file. I ask first so if I don't have the original file I will do it your way, and if i have the file i will use the your above way tells me
> 
> To install nugget software on Mac, head over to code page and download the Mac software version check it well before proceeding the download. After that let me know

I have successfully deleted nugget tweak and my ìace id working again! Thank you😆

**Comment by MasterMind-del** [comment]
> > > > > > > I have iphone 14 pro max and it run ios 18.1 stable. I forgot to read the warning and now i broken minimuxer, i use nugget mobile to spoof device and enable apple intelligent and now my face id not working. How to revert device to default as before using nugget mobile without loss any data?
> > > > > > 
> > > > > > 
> > > > > > Follow the instructions on #185 to solve that issue quick
> > > > > 
> > > > > 
> > > > > Can i update to a newer version when available to revert device back to default and remove apple intelligent, and face id work again?
> > > > 
> > > > 
> > > > If you don’t want to use any nuggets feature then just plug in your phone and head it to apply, select the file you created on the mobile device and hit apply. This will help you to restore the device to the default settings
> > > 
> > > 
> > > And can i remove tweak using the mobile ges file, i don't have org mobile ges file. I ask first so if I don't have the original file I will do it your way, and if i have the file i will use the your above way tells me
> > 
> > 
> > To install nugget software on Mac, head over to code page and download the Mac software version check it well before proceeding the download. After that let me know
> 
> I have successfully deleted nugget tweak and my face id working again! Thank you😆

😅
