### ISSUE TITLE
iOS 18.2 (22C5142a) Support, When Could it Happen?

### ISSUE THREAD

**Issue by GermanBiased** [leminlimez/Nugget#240]
I figured out about Nugget today after i updated to this version. I don't know if me not installing would allow for compatibility, but when will support be enabled for this version?

**Comment by voyyagge** [comment]
Sparserestore работает на всех версиях iOS 17.0-17.7 и iOS 18.0-18.1 бета-версия 4. Есть частичная поддержка iOS 17.7.1 и iOS 18.1b5-18.2 бета-версия 2.

Не поддерживается бета-версия 3 (публичная бета-версия 2) iOS 18.2 для разработчиков и более поздние версии.

**Comment by GermanBiased** [comment]
Когда же тогда его можно будет поддержать?

**Comment by leminlimez** [comment]
no
