### ISSUE TITLE
Mobile gestalt

### ISSUE THREAD

**Issue by voyyagge** [leminlimez/Nugget#241]
To roll back changes to nugget, do I need to use a new mobile gestalt (counterfeit) or the old one?

**Comment by unknownplayer111** [comment]
what can you do in custom gestalt key?

**Comment by leminlimez** [comment]
old one or click the reset mobile gestalt button

**Comment by unknownplayer111** [comment]
am talking about the option in mobliegestalt at the bottom custom gestalt keys? am ask if you can add stuff to the phone system?
