### ISSUE TITLE
does it work with only public/developer beta?

### ISSUE THREAD

**Issue by lokmie** [leminlimez/Nugget#243]
I have an iPhone 15 running iOS 18.1.1 - release.

I tried to enable Apple Intelligence in the Nugget app (I selected iPhone 15 Pro). I chose the Gestalt file, and my iPhone restarted, but Apple Intelligence wasn’t enabled (still Siri). Do I need to install the beta version on my phone?

**Comment by SerStars** [comment]
> Sparserestore works on all versions iOS 17.0-17.7 and iOS 18.0-18.1 beta 4. There is partial support for iOS 17.7.1 and iOS 18.1b5-18.2 beta 2.

> iOS 18.2 developer beta 3 (public beta 2) and newer is not supported.
