### ISSUE TITLE
Enabling iPhone X gestures on iPhone SE (2020) causes red rdar top bar to appear

### ISSUE THREAD

**Issue by TheOliveOli38** [leminlimez/Nugget#25]
FYI, this doesn't happen when enabling Dynamic Island.
(I'm on iOS 18.1 beta 4 by the way)

![image](https://github.com/user-attachments/assets/f384f4df-3175-4a32-a1fc-63f72ae4eca8)

**Comment by leminlimez** [comment]
I am implementing a fix next update but I am not sure what the resolution is supposed to be

**Comment by GuoqSun** [comment]
SE3 also has this issue.

**Comment by TheOliveOli38** [comment]
It's been fixed, although it's stretched on the screen because of the different aspect ratios (which tbf is to be expected)
![IMG_0129](https://github.com/user-attachments/assets/9c0316e8-54fc-48ce-b068-c272e4e6c41c)
