### ISSUE TITLE
It says "ConnectionTerminatedError()' on iPadOS 18.2(22C5142a)

### ISSUE THREAD

**Issue by WebYogurt** [leminlimez/Nugget#251]
![image](https://github.com/user-attachments/assets/9d9577c5-2b11-4968-a00e-ad2550f3b276)
When I Apply Changes, it's alert this.

_iPad Air 5 Generation (iPadOS 18.2    22C5142a)
Mac mini 2014 late (MacOS 15.0) (use OpenCore-Patcher)_

**Comment by leminlimez** [comment]
you are using an outdated version of nugget. Also, read the readme
