### ISSUE TITLE
Feature request：calculator and OCR

### ISSUE THREAD

**Issue by qisudi** [leminlimez/Nugget#253]
Feature request: Enable **calculator** function on iPads with iPadOS 18 below; enable **OCR** function on unsupported devices.

**Comment by SerStars** [comment]
I really want to know how you're gonna get the iPadOS 18 calculator on versions below 18

**Comment by qisudi** [comment]
> I really want to know how you're gonna get the iPadOS 18 calculator on versions below 18

I once thought that this method could be achieved just like enabling Stage Manager for unsupported devices. After all, I am not a professional in this field.
