### ISSUE TITLE
Charge limit is not working

### ISSUE THREAD

**Issue by iPhone12MiniUser** [leminlimez/Nugget#26]
Hello Leminlimez, i have a issue with a charge limit feature. I already set the % that I want but it doesn’t stop at the % that i set and my phone keeps charging to 100%, how to fix that? If you find a way sir, please update “**_Nugget_**” and fix this problem. Thank You!🙏
![IMG_0838](https://github.com/user-attachments/assets/99cf4c1e-217f-4232-9ee4-f34cf8445542)

**Comment by iPhone12MiniUser** [comment]
Oh yeah I forgot, BTW Im using 12 Mini

**Comment by Crxaw** [comment]
Reapply tweak from ur OG plist then its fixed.

**Comment by Crxaw** [comment]
> > Reapply tweak from ur OG plist then its fixed.
> 
> I already reapply it before and i reapply it again and still not working, i try to “restart plist file” and still not working even i add a new mobilegestalt, can you find another way that works?

Close Issue request fix is on discord.
