### ISSUE TITLE
Nugget has a virus again bro

### ISSUE THREAD

**Issue by connorrosco** [leminlimez/Nugget#273]
![image](https://github.com/user-attachments/assets/03453271-ca94-4ae2-8107-fb8435085d5f) come on man 😳 the detected virus is from windows defender

**Comment by MICHAEL-888** [comment]
i guess you are joking 🙃

**Comment by leminlimez** [comment]
windows defender is stupid
reuploaded version seemed to fix it

**Comment by connorrosco** [comment]
> windows defender is stupid
> 
> reuploaded version seemed to fix it

Nope same virus I'll show a pic
