### ISSUE TITLE
partially support

### ISSUE THREAD

**Issue by Ak-2077** [leminlimez/Nugget#280]
nugget shows partially support what to do ?

**Comment by ZodchiyTeney** [comment]
Same problem. Install 18.2

**Comment by leminlimez** [comment]
read the readme

**Comment by ZodchiyTeney** [comment]
tnx. sad

**Comment by Ak-2077** [comment]
my phone is running on 18.2 but it shows partially supported what to do ?

**Comment by leminlimez** [comment]
downgrade to 18.1.1 and stop making github issues bruh
