### ISSUE TITLE
iOS 18.2 support? (build 22C152)

### ISSUE THREAD

**Issue by A70411** [leminlimez/Nugget#281]
I am on iOS 18.1 stable version (build 22B83) on an iPhone 11. Not yet updated to iOS 18.2.

Does Nugget support mobilegestalt tweaks on iOS 18.2 stable version (build 22C152) ? And do the tweaks work on the 18.2 software as well? If so then which version of Nugget should I use if I update to iOS 18.2 stable?

**Comment by OneNougat** [comment]
No, only 18.2 beta 3 (public 2)

**Comment by A70411** [comment]
Ok

**Comment by leminlimez** [comment]
no
