### ISSUE TITLE
Virus still (same one)

### ISSUE THREAD

**Issue by connorrosco** [leminlimez/Nugget#287]
https://github.com/user-attachments/assets/0e90dc78-8fb1-427e-ad5f-559f068b715c and chrome recognizes the virus too not just windows defender

**Comment by A70411** [comment]
Same, detects the virus on any browser when downloading v4.2.1

**Comment by advvvrt** [comment]
When trying to install any version of Nugget, it says that a virus is detected. Does anyone know how to fix this?

**Comment by advvvrt** [comment]
> I don’t know any fix for it. The last version that I managed to download without a virus detected was v4.1Sent from my Apple WatchOn 13 Dec 2024, at 13:58, advvvrt ***@***.***> wrote: When trying to install any version of Nugget, it says that a virus is detected. Does anyone know how to fix this? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

same, but I hope someone knows how to fix this or that it will be resolved soon

**Comment by advvvrt** [comment]
![image](https://github.com/user-attachments/assets/6b557a6f-f840-472d-a3d7-b531fce68e9c)

i can download 4.1 and lower, but new versions..

**Comment by leminlimez** [comment]
This is definitely a pyinstaller issue, I am going to have to figure out something else

**Comment by leminlimez** [comment]
I have manually compiled the bootloader in v4.2.1. Try downloading it from the releases page again

**Comment by connorrosco** [comment]
> I have manually compiled the bootloader in v4.2.1. Try downloading it from the releases page again

Yay thanks limenlimez IT FINALLY WORKS THANKS SO MUCH
