### ISSUE TITLE
Can’t hear Siri/Apple intelligence

### ISSUE THREAD

**Issue by mahmoudfaleh** [leminlimez/Nugget#29]
**[Btw if anyone is asking how I got it after my problem that I said in the old ticket, I restored into Beta 4]**

After installing apple intelligence  I can no longer hear Siri 

I checked
•Volume
•Focus Modes
•Silent Mode

**Comment by mahmoudfaleh** [comment]
Btw I cannot type to ask Siri

**Comment by Ronizairi** [comment]
settings -> apple intelligence and siri -> siri responses -> prefer spoken responses. this worked for me

**Comment by mahmoudfaleh** [comment]
Found solution: settings -> apple intelligence and siri -> siri responses -> prefer spoken responses. this worked for  

Sorry For Not Closing it
