### ISSUE TITLE
Disable Region Restrictions not work on 18.2

### ISSUE THREAD

**Issue by Lysonlee97** [leminlimez/Nugget#295]
I upgraded to the latest iOS 18.2 but I've noticed that I'm getting sound again when taking pictures. I updated to the latest version of nuggets but didn't in see any options for it. Is this feature not supported on iOS 18.2?

Phone Model：iPhone 16 Pro
System Version： iOS18.2
Region: Japan

**Comment by leminlimez** [comment]
no, never will be

read the readme
