### ISSUE TITLE
iOS 18.0.1 is supported?

### ISSUE THREAD

**Issue by adofse** [leminlimez/Nugget#30]
From my understanding, iOS 18.0.1 was out after iOS 18.1 beta 5 which patched SparseRestore.

It is not confirmed that iOS 18.0.1 is supported or not.

**Comment by leminlimez** [comment]
it isnt even out why did you create an issue for it

**Comment by adofse** [comment]
Oh I just misunderstood. I was wondering if iOS 18 22A3354 is supported or not.
My new iPhone 16 Pro has iOS 18.0 22A3351 installed like described below.

> Nor is it a patch release that’s not showing up as iOS 18.0.1 because of a bug. That’s not it either. [One Reddit user](https://www.reddit.com/user/ThannBanis/) described it like this: **“As the initial batch of iPhone 16s shipped before 18.0.0 was released they had a special built installed at the factory. The build number is 22A3351, iOS 18.0.0 for general release has a build number of 22A3354.** Since it’s higher your iPhone 16 sees this as an update.”

https://www.forbes.com/sites/davidphelan/2024/09/26/ios-18-urgent-update-notice-already-issued-for-all-iphone-16-users/

**Comment by AlexTech01** [comment]
18.0 22A3351 is supported, if 18.0.1 releases they'll probably patch it there
