### ISSUE TITLE
Wiki: How daemon modifications works

### ISSUE THREAD

**Issue by moon-cacke** [leminlimez/Nugget#305]
Daemon modification uses sparserestore to modify a configuration file of com.apple.xpc.launchd which is a service responsible for managing and lunching all daemons, it have a plist file that contains a list of disabled daemon, Nugget modify that file to apply the changes

```
tweaks/basic_plist_locations.py

# Daemons
disabledDaemons = "/var/db/com.apple.xpc.launchd/disabled.plist"

```

**Comment by intika** [comment]
DatabaseDomain
`/var/db`
