### ISSUE TITLE
How to know ActionButton is "cT44WE1EohiwRzhsZ8xEsw"?

### ISSUE THREAD

**Issue by hxhlb** [leminlimez/Nugget#307]
I looked for this key value from the iPhone16PM's MobileGestalt file, but found nothing
How to know whether this key "cT44WE1EohiwRzhsZ8xEsw" that is ActionButton option  displayed?

I'm just trying to find out why the ActionButton option affects the Standby option.

**Comment by chuck00000** [comment]
> https://github.com/PoomSmart/MGKeys/blob/master/deobfuscated.py
> 
> https://github.com/leminlimez/Nugget/blob/main/tweaks/tweaks.py
> 
> "cT44WE1EohiwRzhsZ8xEsw": "RingerButtonCapability",
> 
> Nice question... I am going to explicitly set that vatiable to false to check if it fix standby (update setting it to false '0' does not change anything)
> 
> Probably iOS does some stuff when that variable is true and those changes remain elsewhere on the phone...

Have anyone tried make  " landscape Face ID" available on iPhone 12 or older Devices? IS this key right?
![IMG_8069](https://github.com/user-attachments/assets/72b3b905-d5d2-4aaf-b240-aab2c5820f1c)

**Comment by hxhlb** [comment]
> https://github.com/PoomSmart/MGKeys/blob/master/deobfuscated.py
> 
> https://github.com/leminlimez/Nugget/blob/main/tweaks/tweaks.py
> 
> "cT44WE1EohiwRzhsZ8xEsw": "RingerButtonCapability",
> 
> Nice question... I am going to explicitly set that vatiable to false to check if it fix standby (update setting it to false '0' does not change anything)
> 
> Probably iOS does some stuff when that variable is true and those changes remain elsewhere on the phone...

Thanks
