### ISSUE TITLE
nugget crashes after a few seconds on windows

### ISSUE THREAD

**Issue by hackerlacker-py** [leminlimez/Nugget#31]

**Comment by Crxaw** [comment]
Legit fix in discord for it dont open dumb github issues 💀

**Comment by Rosiiiie** [comment]
Where is the fix? I'm looking on the Discord server and I'm not seeing it anywhere. I'm also having this issue where the app just closes upon launch. I have Python 3.12.7, and pymobiledevice3 installed via pip. When trying to open Nugget I get an error, "pymobiledevice3.exceptions.ConnectionFailedToUsbmuxdError".
![image](https://github.com/user-attachments/assets/5ddda7c1-8fa5-414a-a349-f242ab6c34ec)

**Comment by Crxaw** [comment]
Use the Windows version of Nugget. https://github.com/leminlimez/Nugget/releases/tag/v3.0

**Comment by Rosiiiie** [comment]
I have tried both. I get the same result, no matter which one I use.

**Comment by Crxaw** [comment]
> I have tried both. I get the same result, no matter which one I use.

Could be your cable not allowing data transfer. OR you don't have itunes installed.

**Comment by Rosiiiie** [comment]
Installing iTunes did work. @hackerlacker-py , try installing the Windows version of iTunes from [here](https://www.apple.com/itunes/) (scroll all the way down and click Windows, do not install from Microsoft Store) and see if that works. :3
