### ISSUE TITLE
"😳 rdar:45025538" red bar at the top of iPhone XR screen with dynamic island

### ISSUE THREAD

**Issue by NuggyNet** [leminlimez/Nugget#33]
Here it is for you, developer

![stupid rdar](https://github.com/user-attachments/assets/b98e68bc-d3c2-4f4c-bf7a-51aad7fac027)

Also I can't update my iOS so I'm on 18.0 Beta 7 forever now

**Comment by leminlimez** [comment]
fix added in v3

**Comment by NuggyNet** [comment]
hold on do i need to restore my iPhone again?
