### ISSUE TITLE
mc Mac days its unsupported and it lets me move to trash but it isn't damaged and I tried a tutorial on how to fix it but I can't fix it btw I am on a Mac OS MacBook Pro 2019 running Mac OS sequoia

### ISSUE THREAD

**Issue by apple-Intelligencefan** [leminlimez/Nugget#37]

**Comment by leminlimez** [comment]
I have not compiled for intel macs, I need someone who has one to do it unfortunately. You can either wait until I find someone or use the python source code

**Comment by somerandomguythatneedshelp** [comment]
you have to download the dependencies that lemin used and then run main_app.py via python on your mac
