### ISSUE TITLE
someone copying you

### ISSUE THREAD

**Issue by ja26gu** [leminlimez/Nugget#39]
this guy [LoveJessyChen](https://github.com/LoveJessyChen) is posting the exact same files as you on "his" [nugget project ](https://github.com/LoveJessyChen/Nugget-iOS). I don't know if it is a trojan or anything like that i just found it.

**Comment by JensonGuffick** [comment]
I've made a ticket to github support, as he may add malware to it, Not a good idea to leave him be.

**Comment by SerStars** [comment]
There's nothing much that can be done other than reporting.
