### ISSUE TITLE
iPhone X gestures for iPhone SE and request to enable music haptics on older iPhones with mobilegestalt modification

### ISSUE THREAD

**Issue by klepsd** [leminlimez/Nugget#41]
I would like to know how I can remove the rdar message at the top of the screen without using the fix rdar in Nugget desktop which makes the screen all stretched. I Also want to know if mobilegestalt can be modified so that music haptics shows up in settings for my unsupported iPhone (SE 3)

**Comment by A70411** [comment]
Same here, for the Music Haptics. Go an iPhone 11 users, I really wish there was a way to enable Music Haptics.

**Comment by SerStars** [comment]
Fixed in the latest version of Nugget (4.1 of currently writing this)
