### ISSUE TITLE
Undetectable Virus on Nugget Files!!!!!

### ISSUE THREAD

**Issue by X19i** [leminlimez/Nugget#47]
![sdd](https://github.com/user-attachments/assets/62427389-1cf5-4313-9e7c-5c642bd8207c)

You're a **foul f*ck** for installing a trojan virus through the files. To make it even worse it's very much undetectable.

**Trojan.Agent.Win32.3992696**

**FYI** downloaded files for programs don't open with google chrome. Dumba*s

**Comment by leminlimez** [comment]
that is a false positive, nugget contains no viruses. You can literally look through the source code itself

**Comment by X19i** [comment]
The screenshot you are looking at is the Windows.zip file and not the app itself that's infected . The application doesn't open up and redirects to more downloads on the chrome browser. It's endless

**Comment by Skythefemboy0o0** [comment]
![Image](https://github.com/user-attachments/assets/565d634c-1e3b-4588-9005-1369f6698d2a)


uhh its gotten worse
