### ISSUE TITLE
How to use 3.0 in MacOS intel

### ISSUE THREAD

**Issue by wolfshadowkd** [leminlimez/Nugget#52]
currently there are only arm version, but my mac is intel. Any way to use 3.0 in my Mac?

**Comment by wolfshadowkd** [comment]
ok i got it

**Comment by rishabhkushx** [comment]
how? please help

**Comment by wolfshadowkd** [comment]
Requirements:

pymobiledevice3
Python 3.8 or newer
Note: It is highly recommended to use a virtual environment:

python3 -m venv .env # only needed once
# macOS/Linux:  source .env/bin/activate
# Windows:      .env/Scripts/activate.bat
pip3 install -r requirements.txt # only needed once
python3 main_app.py
Note: It may be either python/pip or python3/pip3 depending on your path.
