### ISSUE TITLE
Domain name cannot contain a slash (MBErrorDomain/205)

### ISSUE THREAD

**Issue by mohammednabarawy** [leminlimez/Nugget#55]
Applying EU Enabler for region 'SA'...
Traceback (most recent call last):
  File "devicemanagement\device_manager.py", line 175, in apply_changes
  File "Sparserestore\restore.py", line 53, in restore_files
  File "Sparserestore\__init__.py", line 27, in perform_restore
  File "Sparserestore\__init__.py", line 20, in perform_restore
  File "pymobiledevice3\services\mobilebackup2.py", line 140, in restore
  File "pymobiledevice3\services\device_link.py", line 61, in dl_loop
pymobiledevice3.exceptions.PyMobileDevice3Exception: Device link error: {'ErrorCode': 205, 'ErrorDescription': 'Domain name cannot contain a slash (MBErrorDomain/205)', 'MessageName': 'Response'}

**Comment by DrWxlfz** [comment]
I think the EU Enabler is broken, everything else works.

**Comment by mohammednabarawy** [comment]
Even apple intelligence gives me the same error

**Comment by Erisfiregamer1** [comment]
iOS 18.1 Beta 5 is not supported.

**Comment by incog-geek1** [comment]
> Even apple intelligence gives me the same error

same and i'm on iOS 18.1 Beta 4

**Comment by Erisfiregamer1** [comment]
> > Even apple intelligence gives me the same error
> 
> same and i'm on iOS 18.1 Beta 4

If you are getting this error you are on an unsupported version and you have to downgrade. Likely iOS auto updated

**Comment by incog-geek1** [comment]
> > > Even apple intelligence gives me the same error
> > 
> > 
> > same and i'm on iOS 18.1 Beta 4
> 
> If you are getting this error you are on an unsupported version and you have to downgrade. Likely iOS auto updated

but on nugget it says its supported. and it never autoupdated because I have the setting off

**Comment by incog-geek1** [comment]
how do i downgrade to make it supported?
