### ISSUE TITLE
Feature request: disable "ringer-switch" capability

### ISSUE THREAD

**Issue by SMFB7** [leminlimez/Nugget#56]
I checked the Control Center mute module's `Info.plist` (/System/Library/ControlCenter/Bundles/MuteModule.bundle/Info.plist) on my iPhone 11 with iOS 18 dev beta 2, and it had:  
`"CCRequiredDeviceIncapabilities"`  
`"ringer-switch"`  
Which means that the device should lack the ringer-switch capability in order for the mute module to appear. It is no longer controlled by `com.apple.control-center.MuteModule.plist`.  
Thank you.  
You can grab the key to actually use in a MobileGestalt file from https://github.com/PoomSmart/MGKeys/blob/master/deobfuscated.py. Don't forget to credit PoomSmart (and probably others who were involved).

**Comment by SMFB7** [comment]
I am doing a fork for this feature, will report back if the feature works after vacation

**Comment by leminlimez** [comment]
SSV protected system files are not modifiable

**Comment by SMFB7** [comment]
> SSV protected system files are not modifiable

What I meant in this feature request is that a key should be added to the MobileGestalt cache, the file that Nugget modifies, stating that the ringer-switch capability isn't present, as the module's Info.plist states that `ringer-switch` should be disabled in the MobileGestalt cache. Note the "**In**capabilities" instead of "Capabilities". I think you can just get the code for the Disable Parallax feature but change the key to `ringer-switch`. If it doesn't work, use the encrypted version from MGKeys.  

I got the `Info.plist` file using a-Shell mini, an App Store app (it has read access to system files) by going to the path and using the command "open Info.plist" to open `Info.plist` in the share sheet. Then I saved it to the Files app and opened it via a plist editor. I didn't modify anything.  

`com.apple.control-center.MuteModule` is the configuration file in either /User/Preferences or /var/Managed Preferences/mobile that defines whether the mute switch in the Control Center (not Settings and Shortcuts though) should be available. The Cowabunga Lite tweak that I think relied on this configuration file no longer works on iOS 18.  

Thank you.

**Comment by incog-geek1** [comment]
@leminlimez
