### ISSUE TITLE
EU enabler not work 

### ISSUE THREAD

**Issue by Heisvictor** [leminlimez/Nugget#59]
I am using iPhone 11 Pro Max X, and I am running on iOS 18.0.1 so I tried the EU enabler, after nugget have restarted my phone, I tried to download alstore and do something but it did not work which mean the EU enabler did not work. I used window 10 for the nugget. So please can you tell me what the problem is and how to solve it? Thank you

**Comment by incog-geek1** [comment]
@leminlimez

**Comment by leminlimez** [comment]
will never work on ios 18
