### ISSUE TITLE
support 18.1 beta 5

### ISSUE THREAD

**Issue by b33pca** [leminlimez/Nugget#60]
is there any plans to support IOS 18.1 beta 5?

**Comment by bentoon00** [comment]
read the description.

**Comment by b33pca** [comment]
wanted to use aod on my iphone 16 where 18.1 beta 5 is installed. will it work in the future?

**Comment by JensonGuffick** [comment]
**If you switch from developer beta to public beta, it'll show beta 4, you can roll back!**
Just doing it on my phone now
