### ISSUE TITLE
Will updating iOS 17.6.1 to iOS 17.7 or higher remove Eu Enabler?

### ISSUE THREAD

**Issue by InkxtheSquid** [leminlimez/Nugget#64]
this is a genuine question, because I don't know if I have to remove app marketplaces before updating, I'm just worried if I do a software update my phone might get bricked

**Comment by AlexTech01** [comment]
EUEnabler only works on 17.4.x

**Comment by InkxtheSquid** [comment]
> EUEnabler only works on 17.4.x

I'm asking if euenabler disappears after updating

**Comment by InkxtheSquid** [comment]
I updated my phone to iOS 18.1.1 using iTunes on my computer and I can confirm that it removes EU Enabler, I guess that's okay so far, I wanted to remove it anyway, well it's time to wait for app marketplaces to come to America!
