### ISSUE TITLE
AttributeError: 'RdarFixTweak' object has no attribute 'di_type'. Did you mean: 'edit_type'?

### ISSUE THREAD

**Issue by viperflame** [leminlimez/Nugget#68]
![Screenshot (33)](https://github.com/user-attachments/assets/097bfab7-495a-4d76-8b40-632c9f05badd)

This error again and again

**Comment by amaannajam** [comment]
Did u select device subtype before applying status bar (fix rdar)

**Comment by leminlimez** [comment]
fixed
