### ISSUE TITLE
"pymobiledive3exception" this is happening on nugget v4.0

### ISSUE THREAD

**Issue by proxutech** [leminlimez/Nugget#79]
![Zrzut ekranu 2024-10-28 162516](https://github.com/user-attachments/assets/17e79ab1-a462-4b69-9fdf-5a377b995838)

**Comment by StoreVia** [comment]
yes the bug started for those who update to 18.1 me too wait for a fix.

**Comment by leminlimez** [comment]
what tweaks are you applying

**Comment by proxutech** [comment]
always on display, iphone 16 pm dynamic island and apple intelligence

**Comment by bnthteam** [comment]
Same problem, because Gestalt file location contains '/' instead of '\'.

**Comment by bnthteam** [comment]
Same problem. AI only

**Comment by proxutech** [comment]
it doesn’t work sadly😭😭

**Comment by proxutech** [comment]
yeah, i went on the other computer and apple intelligence was applied but on my main (computer) its not working
PS.i cant apply apple intelligence on misakax too sadly (on both computers)
and thanks.👍👍

**Comment by StoreVia** [comment]
Once try to restart phone without applying tweaks and try again and again

**Comment by leminlimez** [comment]
it is the apple intelligence toggle causing it

**Comment by leminlimez** [comment]
fixed in v4.0.1
