### ISSUE TITLE
Feature Flag Changer

### ISSUE THREAD

**Issue by disfordottie** [leminlimez/Nugget#8]
A cool feature to add would be a feature flag changer, for old photos, iPhone mirroring on beta 1, new Siri, etc

**Comment by NuggyNet** [comment]
New Siri UI requires iOS 18.1 beta which isn't supported by most devices.

**Comment by disfordottie** [comment]
If I meant legitimately I wouldn't have commented. I mean through the feature flag. Like the settings in cowabunga people where using.
