### ISSUE TITLE
apple itelligence on iphone xr doesn't work

### ISSUE THREAD

**Issue by incog-geek1** [leminlimez/Nugget#81]
when i try to do it, i select apple intelligence i select iphone 16 pro or whatever underneath to spoof and I put in the mobile distalt file or whatever its called and then it shuts down the phone, it turns back on but on a black screen for like 20 sec and then reloads and then i go to settings and the apple intelligence section is not there.

**Comment by MKLit7** [comment]
![image](https://github.com/user-attachments/assets/4f5e10f8-95cd-410b-bdfe-05e04b23a3ed)

**Comment by incog-geek1** [comment]
@leminlimez

**Comment by leminlimez** [comment]
fixed in v4.0.1
