### ISSUE TITLE
Apple AI enabler for SUPPORTED devices (16 Pro) disappears

### ISSUE THREAD

**Issue by MDX-Tom** [leminlimez/Nugget#83]
The Apple AI enabler checkbox in "MobileGestalt" is gone in v4.0. 
The only left options are "Disable region restrictions" and Apple AI enabler for UNSUPPORTED models.
So if i want to enable Apple AI for Chinese 16 Pro models (SUPPORTED), what will be the correct steps?
<img width="970" alt="截屏2024-10-29 10 03 41" src="https://github.com/user-attachments/assets/7bd4731e-3a36-4d21-9162-f587140e34a4">

**Comment by xiaobai151** [comment]
就选个DisableRegion就行了

**Comment by MDX-Tom** [comment]
> 就选个DisableRegion就行了

原来如此！多谢！
