### ISSUE TITLE
error MuxException

### ISSUE THREAD

**Issue by moguerri85** [leminlimez/Nugget#85]
I connected the iPhone 12 mini to the PC and started the nugget application. I get this error

![image](https://github.com/user-attachments/assets/39b5f412-a0b4-4655-b645-908541fe5a46)

**Comment by leminlimez** [comment]
you did not install itunes

**Comment by sithyyyy** [comment]
> you did not install itunes

i have the same issue and this is not fixing it

**Comment by sithyyyy** [comment]
![image](https://github.com/user-attachments/assets/53c8d370-3fb2-47f2-89e2-f0ae0e41fd56)

**Comment by leminlimez** [comment]
itunes from the website not from the microsoft store

**Comment by sithyyyy** [comment]
it is the website version i even reinstalled and its still not working. i am also getting ERROR with lockdown device with UUID in the cmd window
