### ISSUE TITLE
Eligibility tweaks dont pop up on the nugget app after installing plz help

### ISSUE THREAD

**Issue by qweerttzu** [leminlimez/Nugget#89]
I installed everything as said in the video but the eligibility option is missing bc of that i cant install apple inteligence

**Comment by rabeh968** [comment]
Me too some probleme , i lose siri intelligence after activate ?

**Comment by qweerttzu** [comment]
![image](https://github.com/user-attachments/assets/bceb4f4b-456c-49ed-a4ab-839e11d2b46a)

**Comment by leminlimez** [comment]
your device is not on 18.1

**Comment by maksc1** [comment]
> your device is not on 18.1

And if the system is higher than this version, then this setting will never be available again?
