### ISSUE TITLE
ERROR with lockdown device with UUID xxx

### ISSUE THREAD

**Issue by Kabbutino** [leminlimez/Nugget#91]
hi, i've got this problem, after i flash some mods and idk how to resolve this problem. someone can help me plsss? thanks

**Comment by bubbleee030** [comment]
Don't know what cause this, but I fixed this problem by redownload nugget and use the new nugget.exe to apply my plist. Hope this will help.

**Comment by leminlimez** [comment]
better error handling in v4.0.1 addresses this
