### ISSUE TITLE
Be able to always have antirevoke on our devices

### ISSUE THREAD

**Issue by NoozPrime** [leminlimez/Nugget#94]
So when we use esign with a cert we need the dns all the time i wish there was a way to always block the domains on devices instead of using a dns for it

**Comment by incog-geek1** [comment]
@leminlimez

**Comment by SerStars** [comment]
Please don't use Esign, it sells your data to China.
Use [Feather](https://github.com/khcrysalis/Feather) by [Samara](https://github.com/khcrysalis/) instead.
