### ISSUE TITLE
Dial pad look abnormal after fixing Dynamic Island status bar on iPhone 13 Pro

### ISSUE THREAD

**Issue by anth4m** [leminlimez/Nugget#97]
![IMG_2100](https://github.com/user-attachments/assets/2e45f2df-10f3-4340-9eee-ea45cf55e330)
My keypad looks small after changing the resolution by applying status bar fix. I failed to restore back to the original resolution after restoring back the original Mobile Gestalt file. Is there a way to revert back to the original resolution? Or is there a solution for the dial pad? iPhone 13 Pro, iOS 18.1

**Comment by anth4m** [comment]
UPDATE: Fixed by "Remove all tweaks" temporarily, as it reverts back to the original resolution. I'm still curious if there's a way to fix the dial pad in other resolutions though.

**Comment by leminlimez** [comment]
this is because the rdar fix changes the resolution, it cant be fixed
