### ISSUE TITLE
FEATURE REQUEST: BLOCK U?PDATES

### ISSUE THREAD

**Issue by luhgarlicbread** [leminlimez/Nugget#98]
Is it possible to implement the feature of blocking iOS updates into Nugget? I am unable to do the typical "tvOS profile" method due to my organization blocking them.
Thanks & God bless!

**Comment by lslqtz** [comment]
ref: https://github.com/rponeawa/thermalmonitordDisabler

**Comment by luhgarlicbread** [comment]
> ref: https://github.com/rponeawa/thermalmonitordDisabler

I will try this. Thank you!

**Comment by luhgarlicbread** [comment]
> ref: https://github.com/rponeawa/thermalmonitordDisabler

Using these tools, is there a way to also delete the currently downloaded update from storage? or- How can I do that?

**Comment by SerStars** [comment]
Added in 4.1.
