### ISSUE TITLE
muxexception error

### ISSUE THREAD

**Issue by sithyyyy** [leminlimez/Nugget#99]
I have tried to fix it and cant. I have itunes installed.
@leminlimez 
![image](https://github.com/user-attachments/assets/e8897aec-beb2-46eb-be7b-3c1e45f25557)

**Comment by Okayatharva-glitch** [comment]
I'm getting the same error found any way to fix this ?
I got my faceId disabled cant revert without bypassing this error

**Comment by leminlimez** [comment]
apple devices app on the windows store

**Comment by Okayatharva-glitch** [comment]
thanks for the quick reply!
okay downloading it right away
what do i do next

**Comment by Okayatharva-glitch** [comment]
Thanks a lot it fixed my issue !

**Comment by sithyyyy** [comment]
apple devices is stuck on this screen after i click trust on my phone
![{63BBFE3A-2F27-4B43-BD7B-7267C4CA8DF2}](https://github.com/user-attachments/assets/d996430f-bed5-45fc-8962-a5c272f8b9b1)
